admins = {
	{ name = "Cena", title = "Owner", accountName = "Cena" },
	{ name = "KaliBwoy", title = "Server Manager", accountName = "KaliBwoy" },
	{ name = "Kreator", title = "Server Manager", accountName = "Goldberg" },
	{ name = "Bierbuikje", title = "Developer", accountName = "bierbuikje" },
	{ name = "Mihoje", title = "Developer", accountName = "Mihoje" },
	{ name = "MoshPit", title = "Map Manager", accountName = "MoshMosh" },
	{ name = "Dubby", title = "Map Manager", accountName = "michael" },
	{ name = "Jack123", title = "Mother Russia", accountName = "Jack123" },
	{ name = "Stig", title = "Old Admin", accountName = "Stig" },
	{ name = "Abrahax", title = "Kadabrahax", accountName = "abrahax" },
	{ name = "LeTearDuGemeaux", title = "Web Admin", accountName = "AnthonyVz" },
	{ name = "BlueYoshi", title = "Admin", accountName = "BlueYoshi97" },
	{ name = "Jap", title = "Admin", accountName = "jap3" },
	{ name = "Haxardous", title = "Admin", accountName = "Axa" },
}
