admins = {
	{ name = "Ywa", title = "Founder/Owner", accountName = "Ywa" },
	{ name = "FantomicanYoshi", title = "Manager", accountName = "BlueYoshi97" }, 
	{ name = "Bierbuikje", title = "developer", accountName = "bierbuikje" },
	{ name = "Bob_Taylor", title = "Map Manager", accountName = "Bob_Taylor" },
	{ name = "Moh", title = "Map Manager", accountName = "Moh" },
	{ name = "MoshPit", title = "Map Manager", accountName = "MoshMosh" },
	{ name = "neox.", title = "Map Assistant", accountName = "neox" },
	{ name = "Goldberg", title = "Map Assistant", accountName = "Goldberg" },
	{ name = "r0cK", title = "Event Admin", accountName = "r0cK" },
	{ name = "Jack123", title = "Mother Russia", accountName = "Jack123" },
	{ name = "Stig", title = "Old Admin", accountName = "Stig" },
	{ name = "Hulpje", title = "Dota Admin", accountName = "hulpje" },
	{ name = "Besweeet", title = "4th Admin", accountName = "besweeet" },
	{ name = "Santiii733", title = "Re-Volt Master", accountName = "santiii733" },
	{ name = "Flipper", title = "Admin", accountName = "KoM|Flipper" },
}
