-------------------------------------
-- Code generated by DKR QT to Lua 0.1.7 --
-- Source: shop.ui --
-- Date:  15/07/2012 - 19:28:59 --
-------------------------------------
local gui
function build_mainGCShopWindow()

	gui = {}
	gui._placeHolders = {}

	local screenWidth, screenHeight = guiGetScreenSize()
	local windowWidth, windowHeight = 750, 540
	local left = screenWidth/2 - windowWidth/2
	local top = screenHeight/2 - windowHeight/2
	gui["_root"] = guiCreateWindow(left, top, windowWidth, windowHeight, "", false)
	guiWindowSetSizable(gui["_root"], false)

	gui["shopTabs"] = guiCreateTabPanel(10, 70, 730, 460, false, gui["_root"])

	gui["tab_home"] = guiCreateTab("", gui["shopTabs"])

	gui["scrollAreaHome"] = guiCreateScrollPane(60, 30, 621, 360, false, gui["tab_home"])

	gui["labelHome"] = guiCreateLabel(11, 11, 581, 251, "", false, gui["scrollAreaHome"])
	guiLabelSetHorizontalAlign(gui["labelHome"], "left", true)
	guiLabelSetVerticalAlign(gui["labelHome"], "top")

	gui["tabDonate"] = guiCreateTabPanel(11, 271, 281, 251, false, gui["scrollAreaHome"])

	gui["tab_Donate"] = guiCreateTab("", gui["tabDonate"])

	gui["labelDonate"] = guiCreateLabel(10, 10, 251, 210, "", false, gui["tab_Donate"])
	guiSetEnabled(gui["labelDonate"], false)
	guiLabelSetHorizontalAlign(gui["labelDonate"], "left", true)
	guiLabelSetVerticalAlign(gui["labelDonate"], "top")
	guiLabelSetColor(gui["labelDonate"], 120, 120, 120)

	gui["tabWin"] = guiCreateTabPanel(301, 271, 291, 251, false, gui["scrollAreaHome"])

	gui["tab_Win"] = guiCreateTab("", gui["tabWin"])

	gui["labelWin"] = guiCreateLabel(10, 10, 261, 210, "", false, gui["tab_Win"])
	guiSetEnabled(gui["labelWin"], false)
	guiLabelSetHorizontalAlign(gui["labelWin"], "left", true)
	guiLabelSetVerticalAlign(gui["labelWin"], "top")
	guiLabelSetColor(gui["labelWin"], 120, 120, 120)

	gui["labelHome_2"] = guiCreateLabel(11, 531, 581, 100, "", false, gui["scrollAreaHome"])
	guiLabelSetHorizontalAlign(gui["labelHome_2"], "left", true)
	guiLabelSetVerticalAlign(gui["labelHome_2"], "top")

	gui["tab_login"] = guiCreateTab("", gui["shopTabs"])

	gui["label_step2"] = guiCreateLabel(180, 40, 351, 131, '', false, gui["tab_login"])
	guiLabelSetHorizontalAlign(gui["label_step2"], "left", true)
	guiLabelSetVerticalAlign(gui["label_step2"], "top")

	gui["labelLoginInfo"] = guiCreateLabel(200, 280, 361, 101, "", false, gui["tab_login"])
	guiLabelSetHorizontalAlign(gui["labelLoginInfo"], "left", true)
	guiLabelSetVerticalAlign(gui["labelLoginInfo"], "center")

	gui["edit_pass_gc"] = guiCreateEdit(340, 250, 113, 20, "", false, gui["tab_login"])
	guiEditSetMaxLength(gui["edit_pass_gc"], 32767)
	guiEditSetMasked(gui["edit_pass_gc"], true)

	gui["buttonLink"] = guiCreateButton(340, 190, 91, 23, "", false, gui["tab_login"])
	if on_buttonLink_clicked then
		addEventHandler("onClientGUIClick", gui["buttonLink"], on_buttonLink_clicked, false)
	end

	gui["edit_user_gc"] = guiCreateEdit(340, 220, 113, 20, "", false, gui["tab_login"])
	guiEditSetMaxLength(gui["edit_user_gc"], 32767)

	gui["label_user_gc"] = guiCreateLabel(200, 220, 121, 16, "", false, gui["tab_login"])
	guiLabelSetHorizontalAlign(gui["label_user_gc"], "left", false)
	guiLabelSetVerticalAlign(gui["label_user_gc"], "center")

	gui["label_pass_gc"] = guiCreateLabel(200, 250, 121, 16, "", false, gui["tab_login"])
	guiLabelSetHorizontalAlign(gui["label_pass_gc"], "left", false)
	guiLabelSetVerticalAlign(gui["label_pass_gc"], "center")

	gui["label_Web"] = guiCreateLabel(200, 190, 151, 16, "mrgreengaming.com", false, gui["tab_login"])
	guiSetFont(gui["label_Web"], "default-bold-small")
	guiLabelSetHorizontalAlign(gui["label_Web"], "left", false)
	guiLabelSetVerticalAlign(gui["label_Web"], "center")

	gui["labelGreencoinsShadow1"] = guiCreateLabel(550.5, 24.5, 191, 41, "", false, gui["_root"])
	guiLabelSetHorizontalAlign(gui["labelGreencoinsShadow1"], "right", false)
	guiLabelSetVerticalAlign(gui["labelGreencoinsShadow1"], "center")

	gui["labelGreencoins"] = guiCreateLabel(550, 25, 191, 41, "", false, gui["_root"])
	guiLabelSetHorizontalAlign(gui["labelGreencoins"], "right", false)
	guiLabelSetVerticalAlign(gui["labelGreencoins"], "center")
	setMainGCShopWindowText()
	return gui, windowWidth, windowHeight
end

function setMainGCShopWindowText()
	guiSetText(gui["_root"], _("GreenCoins Shop (F6 to close)"))
	guiSetText(gui["tab_home"], _("Home"))
	guiSetText(gui["labelHome"], _(
[[Hello and welcome to the Grand Guide to GreenCoins!

WTF are Green-Coins?
--------------------
They are a currency used by the Mr. Green community. We created a global database where players can connect their Green-Coins to one account, and use them on different game servers.

What can I do with Green-Coins in MTA?
-------------------------------
You can buy car mods, skins, or other fancy stuff that you can use ingame!

What do I need to get Green-Coins?
----------------------------------
You need to register a Green-Coins account, go to the "Register" tab for more info.
How do I get Green-Coins?
------------------------------------------

]]))
	guiSetText(gui["tab_Donate"], _("Donate"))
	guiSetText(gui["labelDonate"], _(
[[You can donate. For each euro donated you get 1000 GreenCoins.

How do I donate?
-----------------------
Go to mrgreengaming.com and click "Green-Coins".

If you log into your account, you see a conveniently placed button that says "Send donation".

Just follow the simple instructions on there and you're done!

]]))
	guiSetText(gui["tab_Win"], _("Win"))
	guiSetText(gui["labelWin"], _(
[[The second way to get GreenCoins is racing.

Winning races: you earn GC based on the map length.
New toptime: If you're good and manage to get a new top1, top2 or top3 you will earn extra GC!
Even if you didnt win or finish you earn Green-Coins based on your results, so don't give up!


]]))
	guiSetText(gui["labelHome_2"], _("More info in the Network section or use this link: http://forums.mrgreengaming.com/topic/2183-the-grand-guide-to-green-coins/"))
	guiSetText(gui["tab_login"], _("Register / Login"))
	guiSetText(gui["label_step2"], _("1. Register an account on our Forums ( https://mrgreengaming.com/forums )\n\n\n2. Log in using your Forums account:"))
	guiSetText(gui["buttonLink"], _("Login"))
	guiSetText(gui["label_user_gc"], _("Username or email:"))
	guiSetText(gui["label_pass_gc"], _("Password:"))
end
addEventHandler("onClientPlayerLocaleChange ", root, build_mainGCShopWindow)
